# Numpy

In [3]:
import numpy as np
import time

In [5]:
a=[1,2,3]
b=[4,5,6]
list(zip(a,b))


[(1, 4), (2, 5), (3, 6)]

In [8]:
a = list(range(100000000))
b = list(range(100000000))

start_t = time.time()
c = [x+y for x,y in zip(a,b)]
end_t = time.time()

diff = end_t-start_t
print(diff)

20.56193995475769


In [10]:
a = np.arange(100000000)
b = np.arange(100000000)

start_t = time.time()
c = a+b
end_t = time.time()

diff = end_t-start_t
print(diff)

1.3713159561157227


# 1 np.array()

In [12]:
array_n1 = np.array([1,2,3])

In [14]:
print(array_n1)
print(type(array_n1))
print(type(array_n1[0]))

[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [15]:
array_n2 = np.array([1,2,3], dtype=np.int8)
print(type(array_n2))
print(type(array_n2[0]))

<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [17]:
array_n2 = np.array([1,2,"3"], dtype=np.int8)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))


[1 2 3]
<class 'numpy.ndarray'>
<class 'numpy.int8'>


In [18]:
array_n2 = np.array([1,2,"3"], dtype=np.float16)
print(array_n2)
print(type(array_n2))
print(type(array_n2[2]))

[1. 2. 3.]
<class 'numpy.ndarray'>
<class 'numpy.float16'>


# 2. np.arange(start, stop, step)

In [19]:
print(np.arange(5))

print(np.arange(1, 10, 2))

np_arange = np.arange(1, 10, 2)
print(type(np_arange))

[0 1 2 3 4]
[1 3 5 7 9]
<class 'numpy.ndarray'>


# np.linspace(start, stop, num=x)
np.linspace(start, stop, num) generates num evenly spaced values between start and stop, inclusive.



In [20]:
np_linspace = np.linspace(1,100,4)
print(np_linspace)
print(type(np_linspace))

[  1.  34.  67. 100.]
<class 'numpy.ndarray'>


In [22]:
for i in np.linspace(1,10,10):
    print(i)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


# np.zeros(shape)

In [25]:
npz_1 = np.zeros(5)
npz_1

array([0., 0., 0., 0., 0.])

In [24]:
npz_1.ndim

1

In [26]:
npz_2 = np.zeros((5,5))
print(npz_2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
npz_2.ndim

2

In [28]:
npz_3 = np.zeros((5,5,5))
print(npz_3)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [29]:
npz_3.ndim

3

# np.ones()

In [30]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
np.ones((5,5), dtype=np.int8)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

# np.full()

In [32]:
np.full((5,5), 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
np.full((5,5), 100)

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [35]:
np.full(10, 5)
# np.full(shape, fill_value)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

# np.eye(n)

In [51]:
# np.eye(N, M, k)
#N: number of rows (6)
#M: number of columns (6)
#k: index of the diagonal
np.eye(6, 5, 2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# np.empty(shape)

In [53]:
a = np.full((5,5), 0)
print(a)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [54]:
np.empty((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# np.empty((5, 5), dtype=np.int8) creates a 5×5 NumPy array of type int8 (i.e., 8-bit integers), 
# but does not initialize the entries — meaning the values are random garbage values that already exist in memory.
np.empty((5,5), dtype=np.int8)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int8)

In [55]:
np.empty((5,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [63]:
import time
# perf_counter() is used to get high-resolution time counter.

start_e = time.perf_counter()
np.empty((5, 5))
end_e = time.perf_counter()
total_e = end_e - start_e
print(total_e)  

5.929201142862439e-05


In [64]:
start_we = time.perf_counter()
np.ones((5, 5))
end_we = time.perf_counter()
total_we = end_we - start_we
print(total_we)

0.0003731250180862844


# np.random.rand(shape)

In [66]:
np.random.rand(5,5)

array([[0.30043334, 0.63158801, 0.37547398, 0.35435096, 0.66099008],
       [0.34087332, 0.60136364, 0.1055888 , 0.95101235, 0.21157062],
       [0.09733358, 0.26876917, 0.91079241, 0.24308009, 0.77368824],
       [0.23604336, 0.82830516, 0.86085607, 0.70765238, 0.96530019],
       [0.82039557, 0.98132127, 0.93187828, 0.71359291, 0.67478775]])

In [67]:
a = np.random.rand(10)*10

In [68]:
a

array([6.68670001, 8.03647832, 2.05307259, 3.08416541, 1.93273608,
       1.69979461, 5.61410404, 5.29452959, 3.49249166, 3.58712067])

In [69]:
a = a.tolist()
a

[6.686700014731447,
 8.036478320765926,
 2.0530725858880174,
 3.084165413676762,
 1.932736076285415,
 1.6997946074368686,
 5.614104038189303,
 5.294529588765311,
 3.4924916609156273,
 3.587120671794932]

In [70]:
a = [int(i) for i in a]
a

[6, 8, 2, 3, 1, 1, 5, 5, 3, 3]

In [71]:
np.random.randint(1, 11, 10)

array([2, 6, 6, 4, 7, 1, 7, 7, 6, 2])

# Questions
- A 1D array of numbers from 0 to 9
- A 3x3 matrix of all 5s
- A 4x4 identity matrix
- 10 evenly spaced numbers between 1 and 100
- A 2x2 array with random values between 0 and 1

In [ ]:
#A 1D array of numbers from 0 to 9
a = np.arange(0,10)
print(a)
print(type(a))

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
# 3x3 matrix of all 5s
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# A 4x4 identity matrix
np.eye(4,4,0)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [79]:
# 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [80]:
# A 2x2 array with random values between 0 and 1
np.random.rand(2,2)

array([[0.27611873, 0.50381394],
       [0.28082342, 0.95801561]])

# Numpy Math Operation


In [3]:
a=[1,2,3]
b=[4,5,6]
a+b

[1, 2, 3, 4, 5, 6]

In [4]:
import numpy as np

In [10]:
# Convert to array
# Vectorize operation
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(type(a+b))

[5 7 9]
<class 'numpy.ndarray'>


In [ ]:
print(a-b)
print(a*b)
print(a/b)

[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [11]:
# Comparison
print(a>b)
print(a<b)
print(a==b)

[False False False]
[ True  True  True]
[False False False]


In [14]:
ans = a>b
print(type(ans[0]))
print(type(ans))

<class 'numpy.bool'>
<class 'numpy.ndarray'>


In [81]:
# Logical Operator
# and, or , not
x=np.array([True, False, True])
y=np.array([False, False, True])

print(np.logical_and(x,y))
print(np.logical_or(x, y))
print(np.logical_not(x))

[False False  True]
[ True False  True]
[False  True False]


In [20]:
# Bitwise operator
a=np.array([1,2,3])
b=np.array([0,1,1])
print(np.bitwise_and(a, b))

[0 0 1]


In [18]:
# Modulus and Power
a=np.array([10,20,30])
b=np.array([3,7,4])
print(np.mod(a,b))
print(np.power(a,b))

[1 6 2]
[      1000 1280000000     810000]


# Scalar Operation


In [21]:
celcius = np.array([0,10,20,30])
to_farenhit = (9/5+32)
print(to_farenhit)

33.8


In [23]:
celcius = np.array([0,10,20,30])

# Broadcasting
print(celcius*to_farenhit)

[   0.  338.  676. 1014.]


In [85]:
celcius = [0, 10, 20, 30]
to_fahrenheit = [(9/5)*temp + 32 for temp in celcius]
print(to_fahrenheit)


celcius = [0,10,20,30]
to_farenhit = ((9/5)+32)
print(celcius*to_farenhit)
# celcius * to_farenhit is invalid: you can’t multiply a list by a float like that (unless multiplying a list by an int to repeat it).




[32.0, 50.0, 68.0, 86.0]


TypeError: can't multiply sequence by non-int of type 'float'

# Common Maths Functions

In [ ]:
a=np.array([1,2,3,4])
print(np.sqrt(a))
print(np.exp(a)) # e^1, e^2
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
# machine learning
# activation function

# sigmoid

x = np.array([-1, 0, 1])
sigmoid = 1 / (1 + np.exp(-x))
print(sigmoid)  

[0.26894142 0.5        0.73105858]


In [33]:
a=np.array([[1,2,3],
           [4,5,6]])


In [88]:
print(np.sum(a, axis=0))
# across all rows, fix the column

print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))



45
45
4.5
2.8722813232690143
0
9


# Matrix Operation

In [39]:
# Elementwise operation
units=np.array([100,200,250])
profits=np.array([10,20,30])
units*profits

array([1000, 4000, 7500])

# Dot Product

In [41]:
house = np.array([1200, 3, 1])
w = np.array([200, 1000, 50000])
print(house.shape)
print(w.shape)

(3,)
(3,)


In [89]:
house = np.array([[1200, 3, 1],
                  [1200, 3, 0],
                  [1000, 3, 0],
                  [1000, 1, 1]])
w = np.array([200, 10000, 50000])
print(np.dot(house, w))

[320000 270000 230000 260000]


In [90]:
print(np.sum(house * w, axis=1)) # multiplication + sum

[320000 270000 230000 260000]


In [46]:
p = np.dot(house,w)
print(p)
print(f"Price of house is {p}")

293000
Price of house is 293000


In [91]:
A = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])
B = np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

In [92]:
print(A.shape)
print(B.shape)

(2, 4)
(2, 4)


In [93]:
print(np.dot(A, B))

ValueError: shapes (2,4) and (2,4) not aligned: 4 (dim 1) != 2 (dim 0)

In [94]:
print(np.dot(A, B.T))

[[30 30]
 [30 30]]


In [95]:
print(A @ B.T)

[[30 30]
 [30 30]]


# Broadcasting

In [47]:
a = np.array([1,2,3])
b = np.array([[10],[20]])
print(a.shape)
print(b.shape)

(3,)
(2, 1)


In [48]:
a+b

array([[11, 12, 13],
       [21, 22, 23]])

In [49]:
b+a

array([[11, 12, 13],
       [21, 22, 23]])

# Creating array from existing data

In [96]:
a = [1,2,3,4]
b = ([[1,2], [2,3]])
c = (10,20,30)

In [98]:
a_npy = np.array(a)
# a_npy.dtype: This shows the data type of the array elements.
# type(a): This shows the type of the object itself — which will almost always be:
print(a_npy, a_npy.dtype, type(a))

[1 2 3 4] int64 <class 'list'>


In [54]:
# vstack
a = np.array([[1,2]])
b = np.array([[3,4]])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[[1 2 3 4]]


In [99]:
# np.char.<function_name>()

# 1. np.add()

# "hello" + "hello"

a = np.array(['hello', 'world'])
b = np.array(['_user', '_123'])

print(np.char.add(a, b))

['hello_user' 'world_123']


In [100]:
# np.char.multiply()

print(np.char.multiply(a, 2))

['hellohello' 'worldworld']


In [101]:
# np.char.upper() / lower() / capitalize()

a = np.array(['hello', 'WORLD'])

print(np.char.upper(a)) 
print(np.char.lower(a)) 
print(np.char.capitalize(a)) 

['HELLO' 'WORLD']
['hello' 'world']
['Hello' 'World']


In [102]:
# np.char.center()

print(np.char.center(a, 11, fillchar='*'))

['***hello***' '***WORLD***']


In [56]:
a = np.array(['data science','machine-learning'])

In [109]:
# np.char.replace(a, old, new) replaces all occurrences of old with new in each string in the array a.
print(np.char.replace(a,'o','*'))

['hell*' 'WORLD']


In [112]:
# np.char.replace()
a = np.array(['data science','machine-learning'])
print(np.char.replace(a, '-', ' '))

['data science' 'machine learning']


In [114]:
# np.char.split()

import numpy as np

a = np.array(['data_science', 'machine_learning', 'deep_learning'])
result = np.char.split(a, sep='_')
print(result)

[list(['data', 'science']) list(['machine', 'learning'])
 list(['deep', 'learning'])]


In [116]:
# np.char.find() / np.char.count()

print(np.char.find(a, 'learn')) 
print(np.char.count(a, 'a'))
print(np.char.count(a, 'data'))
print(np.char.count(a, 'learning'))

[-1  8  5]
[2 2 1]
[1 0 0]
[0 1 1]


# Statistical Functions

In [67]:
data = np.array([1,2,3,4,5,6])

In [71]:
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))
print(np.min(data))
print(np.max(data))
print(np.argmin(data))
print(np.argmax(data))

3.5
3.5
1.707825127659933
2.9166666666666665
1
6
0
5


# Sort , Search, Counting Function

In [118]:
arr = np.array([3,6,1,1,1,1,8,2,5,6])

# Returns a sorted copy of the array (ascending order). The original array remains unchanged.
print(np.sort(arr))

# Returns the indices that would sort the array. Useful for sorting related data in the same order.
print(np.argsort(arr))

# Finds the index where 4 should be inserted in the sorted array to maintain order.
print(np.searchsorted(np.sort(arr),4))

# Returns the sorted unique elements of the array.
print(np.unique(arr))

# Counts the number of occurrences of each integer value (non-negative integers only).      
print(np.bincount(arr))

[1 1 1 1 2 3 5 6 6 8]
[2 3 4 5 7 0 8 1 9 6]
6
[1 2 3 5 6 8]
[0 4 1 1 0 1 2 0 1]


In [77]:
arr_2d = np.arange(8).reshape(2,2,2)

for x in np.nditer(arr):
    print(x)

3
6
1
1
1
1
8
2
5
6


In [79]:
a = np.array([1,2,3])

In [80]:
b = a

In [81]:
b

array([1, 2, 3])

In [82]:
b[0]=100

In [83]:
print(a)
print(b)

[100   2   3]
[100   2   3]


In [84]:
c=a.copy()

In [85]:
c[0]=200
print(a)
print(c)

[100   2   3]
[200   2   3]


In [119]:
a = np.array([1, 2, 3])

b = a.view()

c = a.copy()

In [120]:
b[0] = 10
print(a)

[10  2  3]


In [121]:
c[0] = 20
print(a)

[10  2  3]


In [86]:
a = np.arange(5)
b = a[1:4]
print(np.shares_memory(a,b))

True


In [87]:
a = np.arange(5)
b = a[1:4].copy()
print(np.shares_memory(a,b))

False


In [123]:
a = np.array([[1, 2], [3, 4]])

# Converts the 2D array to a 1D array, returns a view (no new memory allocated, if possible).
print(a.ravel())

# Converts the 2D array to a 1D array, returns a copy (always creates new memory).
print(a.flatten())    

[1 2 3 4]
[1 2 3 4]
